
name: veriposte_flutter
description: Frontend do app VeriPoste

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
